name: Create Tag From Version

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Package Version
        id: get_package_version
        run: echo "PACKAGE_VERSION=$(cat package.json | jq -r '.version')" >> $GITHUB_ENV
      - name: Test
        run: echo $PACKAGE_VERSION
          
